name: zerocracy
on:
  # schedule:
  #   - cron: '17 * * * *'  # Ежечасно
  workflow_dispatch:  # Для ручного запуска
concurrency:
  group: zerocracy
  cancel-in-progress: false
jobs:
  zerocracy:
    runs-on: ubuntu-24.04
    timeout-minutes: 25
    permissions:  # Добавьте этот блок для прав на запись
      contents: write  # Необходим для деплоя на gh-pages
      pages: write     # Если развертывание на GitHub Pages
      id-token: write  # Для OIDC-аутентификации, если нужно
    steps:
      - uses: actions/checkout@v4
      - uses: zerocracy/judges-action@0.15.6
        with:
          token: ${{ secrets.ZEROCRACY_TOKEN }}
          github-token: ${{ secrets.ZEROCRACY_PAT }}  # Оставьте для judges, если нужен API-доступ
          repositories: Djigit387/learning_rep
          factbase: lap.fb
      - uses: zerocracy/pages-action@0.2.0
        with:
          github-token: ${{ github.token }}  # Используйте GITHUB_TOKEN (встроенный) вместо PAT для Pages
          factbase: lap.fb
      - uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          folder: pages
          clean: false
          token: ${{ github.token }}  # Добавьте token: GITHUB_TOKEN для deploy (если не указан, action использует его по умолчанию)
